ccs_user: "{{ ansible_user }}"
tmp_dir: "/tmp"

ccs_prefix: "/home/{{ ccs_user }}/ti"

ccs_major_version: '8'
ccs_minor_version: '2'
ccs_patch_version: '0'
ccs_build_version: '00007'

ccs_common_requirements:
  - "unzip"
  - "libc6:i386"
  - "libpython2.7"

ccs8_requirements:
  - "libgconf-2-4"
  - "libusb-0.1-4"
  - "build-essential"
  - "libgtk2.0-0:i386"
  - "libjson-perl"
  - "libasound2"
  - "libxtst6"
  - "libcanberra0"

ccs7_requirements:
  - "libgconf-2-4"
  - "libusb-0.1-4"
  - "build-essential"
  - "libgtk2.0-0:i386"
  - "libjson-perl"
  - "libasound2"
  - "libxtst6"
  - "libcanberra0"
  - "libxft2"
  - "libxss1"
  - "xvfb"

ccs6_requirements:
  - "libx11-6:i386"
  - "libasound2:i386"
  - "libatk1.0-0:i386"
  - "libcairo2:i386"
  - "libcups2:i386"
  - "libdbus-glib-1-2:i386"
  - "libgconf-2-4:i386"
  - "libgcrypt20:i386"
  - "libgdk-pixbuf2.0-0:i386"
  - "libgtk-3-0:i386"
  - "libice6:i386"
  - "libncurses5:i386"
  - "libsm6:i386"
  - "liborbit2:i386"
  - "libudev1:i386"
  - "libusb-0.1-4:i386"
  - "libstdc++6:i386"
  - "libxt6:i386"
  - "libxtst6:i386"
  - "libgnomeui-0:i386"
  - "libusb-1.0-0-dev:i386"
  - "libcanberra-gtk-module:i386"
  - "gtk2-engines-murrine:i386"
  - "gtk2-engines-pixbuf:i386"

ccs_version: "{{ ccs_major_version }}.{{ ccs_minor_version }}.{{ ccs_patch_version }}.{{ ccs_build_version }}"
ccs_installer_dir: "CCS{{ ccs_version }}_linux-x64"
ccs_installer_zip: "{{ ccs_installer_dir }}.tar.gz"
ccs_installer: "ccs_setup_linux64_{{ ccs_version }}.bin"
ccs_url: "http://software-dl.ti.com/ccs/esd/CCSv{{ ccs_major_version }}/CCS_{{ ccs_major_version }}_{{ ccs_minor_version }}_{{ ccs_patch_version }}/exports/CCS{{ ccs_version }}_linux-x64.tar.gz"
